### ISSUE TITLE
Week 11 Update

### ISSUE THREAD

**Issue by phil-lopreiato** [gw-cs-sd/sd-2017-distributed-opennetvm#2]
## New This Week
 - Manager can route incoming packets from other instances to the proper NF. This involves encapsulating and decapsulating the `onvm_pkt_meta` structure to be sent on the wire as well as the packet data. We have to read/set the `udata64` field in `struct mbuf` with the metadata. [Diff.](http://capstone.lopreiato.me/D16)
 - Submitted manager patch to allow displaying stats on a webpage instead of in the console. This is towards a distributed stats app, as well as improved manager logging to a file. [Diff.](https://github.com/sdnfv/openNetVM-dev/pull/162)

## For Next Week
 - Put stats in zookeeper
 - Test out how dpdk environment works when forked

## My Demo
 - Basic distributed packet routing demo (speed tester -> basic monitor)

https://github.com/gw-cs-sd/sd-2017-distributed-opennetvm/releases/tag/week-11
@twood02

**Comment by twood02** [comment]
What is your setup currently? Two machines directly connected? A switch with multiple machines?  

You talk about encapsulating meta data so the destination will know what NF to give a packet to.  How does that work?  Is the information embedded inside the VXLAN header itself or do you have something like:

VXLAN header
ONVM header
Actual packet

@Grace-Liu may want to make use of some of this stuff or have you run some experiments for her related to VXLAN overheads.

**Comment by phil-lopreiato** [comment]
It's the latter: the `onvm_pkt_meta` struct goes as part of the encapsulated packet's data, after the vxlan header. [All the structs we prepend to the packet](https://github.com/phil-lopreiato/openNetVM/blob/f235ee0ff273b09b3be6fde428fad3b176da62f0/onvm/onvm_mgr/onvm_vxlan.c#L82),  [where the `onvm_pkt_meta` data gets set](https://github.com/phil-lopreiato/openNetVM/blob/f235ee0ff273b09b3be6fde428fad3b176da62f0/onvm/onvm_mgr/onvm_vxlan.c#L148), and [where we decapsulate](https://github.com/phil-lopreiato/openNetVM/blob/f235ee0ff273b09b3be6fde428fad3b176da62f0/onvm/onvm_mgr/onvm_vxlan.c#L184).

The current setup I'm working with is two machines connected by a switch. I'm hoping to get some actual numbers from the speed tester this week
