### ISSUE TITLE
Week 12: ZooKeeper Stats

### ISSUE THREAD

**Issue by phil-lopreiato** [gw-cs-sd/sd-2017-distributed-opennetvm#3]
## New for This Week
 - Store some basic NF stats in ZooKeeper
   - Per NF, store the RX ring utilization percentage
   - Use `ZOO_SEQUENCE` + `ZOO_EPHEMERAL` to create stat nodes for active NFs. In the manger, we simply need to track a mapping of the NF instance ID to the path returned back from ZooKeeper.
   - See [D18](http://capstone.lopreiato.me/D18) and [D19](http://capstone.lopreiato.me/D19)
- Some ZooKeeper cleanup code, see [D17](http://capstone.lopreiato.me/D17)

## Research
I did some reading into how to fork NFs. If we just call `fork` from inside an NF, we won't be able to runt the new copy on a different core (since only the master process can run [`rte_eal_remote_launch`](http://dpdk.org/doc/api/rte__launch_8h.html#a7456c48bfd011b04cc1c17baac5aa058)). Or, we could have the manager start the new NF: could we load the code into shared memory somehow so the manager can access a function pointer somehow, or could we store the command line arguments and have the manager do a `fork`/`exec` kind of thing.

Also, I'm thinking I'm going to have to make a distributed queue using ZooKeeper to track who should start these new NF copies. If an instance is running a service that "needs help", it should be able to atomically "claim" it and fork the existing copy somehow. This shouldn't be all that hard to write, the forking problem is the more difficult one. Any thoughts on that front, @twood02?

https://github.com/gw-cs-sd/sd-2017-distributed-opennetvm/releases/tag/week-12

**Comment by twood02** [comment]
the putting code in shared memory with funciton pointers sounds overly complex to me, so I would avoid that.  I see two options:

1) Don't use fork at all.  Just have some way of starting a new NF process from scratch.  You might assume all NFs run inside docket containers and then use some sort of docker manager API to initiate new containers as needed.

2) Use fork but then find another way to pin the forked process to the appropriate core. You may not be able to call remote launch (which is for making new threads, not processes) but there may be another function you can use to pin a process to a core.  If DPDK doesn't provide that, then the base OS might.  Worst case you can do this outside of the program using ``taskset``.  There must be some system call API for doing this.

**Comment by phil-lopreiato** [comment]
> putting code in shared memory with funciton pointers sounds overly complex to me, so I would avoid that

Agreed, this definitely seems like a pain.

Some combination of (1) and (2) might be required to be able to support running NFs as standalone processes and within docker containers. I'll probably do (2) first, since that's a simpler case (although [docker commit](https://docs.docker.com/engine/reference/commandline/commit/) looks promising).

As far as a syscall interface for `taskset`, there's [`sched_setaffinity`](http://man7.org/linux/man-pages/man2/sched_setaffinity.2.html). I like this approach, I'll have to test it out and see how it interfaces with DPDK.

**Comment by twood02** [comment]
also be prepared for various issues that may arise when using fork in multi-threaded programs.  For example, we know that if the NF manager uses the ``system()`` function to try to execute another program, the manager will crash.  ``system`` should just be calling ``fork`` and then ``execv``, but it seems to be dangerous in multithreaded environments. Some more info here: http://stackoverflow.com/questions/8574815/calling-system-from-multithreaded-program

**Comment by twood02** [comment]
(the basic issue being that if you call fork you are duplicating all of the threads of the parent, so awful things can happen)

**Comment by phil-lopreiato** [comment]
Actually, I think I misread the docs (they weren't all that clear on this), but an NF should be able to run `rte_eal_remote_launch`. This will bind an existing lcore (implemented by a pthread pinned to a CPU core using `pthread_setaffinity_np`) to a function pointer, like an NF's `main` function.

When we start an NF, it is a master thread for its application so it can run `remote_launch` (my misunderstanding was this was only available to the "primary" application, e.g. the manager). So I think we can avoid forking.
